# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'ARTY_A7_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_A7_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_A7_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_A7_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'ARTY_A7_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_A7_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_A7_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/atsm/Documents/Vivado/uBlaze_ARTY_A7/uBlaze_ARTY_A7.srcs/sources_1/bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_A7_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
