# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ARTY_A7/ARTY_A7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7 || ORIG_REF_NAME==ARTY_A7} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_microblaze_0_0/ARTY_A7_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_microblaze_0_0 || ORIG_REF_NAME==ARTY_A7_microblaze_0_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_clk_wiz_0_0/ARTY_A7_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_clk_wiz_0_0 || ORIG_REF_NAME==ARTY_A7_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_axi_uartlite_0_0/ARTY_A7_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_axi_uartlite_0_0 || ORIG_REF_NAME==ARTY_A7_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_mdm_1_0/ARTY_A7_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_mdm_1_0 || ORIG_REF_NAME==ARTY_A7_mdm_1_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_rst_clk_wiz_0_100M_0/ARTY_A7_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==ARTY_A7_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_microblaze_0_axi_periph_0/ARTY_A7_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ARTY_A7_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_dlmb_v10_0/ARTY_A7_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_dlmb_v10_0 || ORIG_REF_NAME==ARTY_A7_dlmb_v10_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_ilmb_v10_0/ARTY_A7_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_ilmb_v10_0 || ORIG_REF_NAME==ARTY_A7_ilmb_v10_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_dlmb_bram_if_cntlr_0/ARTY_A7_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ARTY_A7_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_ilmb_bram_if_cntlr_0/ARTY_A7_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ARTY_A7_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_lmb_bram_0/ARTY_A7_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_lmb_bram_0 || ORIG_REF_NAME==ARTY_A7_lmb_bram_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_axi_intc_0_0/ARTY_A7_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_axi_intc_0_0 || ORIG_REF_NAME==ARTY_A7_axi_intc_0_0} -quiet] -quiet

# IP: bd/ARTY_A7/ip/ARTY_A7_xbar_0/ARTY_A7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_A7_xbar_0 || ORIG_REF_NAME==ARTY_A7_xbar_0} -quiet] -quiet

# XDC: bd/ARTY_A7/ARTY_A7_ooc.xdc
